const actions = {
    //TRANSACTION
    REFRESH_TRANSACTIONS:'REFRESH_TRANSACTIONS',
    //USER
    SET_AUTHENTICATION_STATUS:'SET_AUTHENTICATION_STATUS',
    SET_NOTIFICATIONS:'SET_NOTIFICATIONS',
    SET_ERRORS:'SET_ERRORS',
}

export default actions;