const actions = {
    //TRANSACTION
    REFRESH_TRANSACTIONS:'REFRESH_TRANSACTIONS',
    //USER
    SET_AUTHENTICATION_STATUS:'SET_AUTHENTICATION_STATUS',
    SET_AUTH_COOKIE:'SET_AUTH_COOKIE'
}

export default actions;